Intentionally fail workflow

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -11,4 +11,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Logrado
-        run: echo "Logrado!"
+        run: echo "Lo he logrado!"
+
+      - name: An Error I made
+        run: |
+          echo "Cometí un error!"
+          exit 1
